In [2]:
# Importing the libraries 
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd 

# Importing the database 
dataset = pd.read_csv('E:\\datasets\\Churn_Modelling.csv')


In [3]:
X = dataset.iloc[:, 3:13].values 
Y = dataset.iloc[:, 13].values 
X


array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [4]:
Y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder,OneHotEncoder 
labelencoder_X_1=LabelEncoder() 
X[:,1] = labelencoder_X_1.fit_transform(X[:,1]) 
labelencoder_X_2=LabelEncoder() 
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2]) 
columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(columnTransformer.fit_transform(X), dtype = np.float64)
X = X[:, 1:]
X

array([[0.0000000e+00, 0.0000000e+00, 2.2800000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [1.0000000e+00, 0.0000000e+00, 2.1700000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 1.1100000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 3.1800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 3.8100000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 4.0100000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [15]:
#Splitting the dataset into the Training set and the Test Set 
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2)



In [17]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler() 
X_train = sc.fit_transform(X_train) 
X_test = sc.transform(X_test)


In [18]:
# Importing the Keras libraries and packages 
import keras 
from keras.models import Sequential 
from keras.layers import Dense


In [19]:
#Initializing Neural Network 
classifier = Sequential()


In [20]:
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', 
activation = 'relu', input_dim = 11))


In [22]:
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', 
activation = 'relu'))

#Execute the following line of code to add the output layer:
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', 
activation = 'sigmoid'))


In [23]:
# Compiling Neural Network 
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])


In [24]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 50)


Epoch 1/50
800/800 [==============================] - 2s 969us/step - loss: 0.4880 - accuracy: 0.7983
Epoch 2/50
800/800 [==============================] - 1s 936us/step - loss: 0.4242 - accuracy: 0.7985
Epoch 3/50
800/800 [==============================] - 1s 1ms/step - loss: 0.4175 - accuracy: 0.7985
Epoch 4/50
800/800 [==============================] - 1s 1ms/step - loss: 0.4133 - accuracy: 0.8250
Epoch 5/50
800/800 [==============================] - 1s 1ms/step - loss: 0.4107 - accuracy: 0.8313
Epoch 6/50
800/800 [==============================] - 1s 916us/step - loss: 0.4089 - accuracy: 0.8320
Epoch 7/50
800/800 [==============================] - 1s 907us/step - loss: 0.4074 - accuracy: 0.8330
Epoch 8/50
800/800 [==============================] - 1s 907us/step - loss: 0.4062 - accuracy: 0.8356
Epoch 9/50
800/800 [==============================] - 1s 861us/step - loss: 0.4046 - accuracy: 0.8355
Epoch 10/50
800/800 [==============================] - 1s 918us/step - loss: 0.4023 - ac

In [25]:
# Predicting the Test set results 
y_pred = classifier.predict(X_test) 
y_pred = (y_pred > 0.5)

new_prediction = classifier.predict(sc.transform 
(np.array([[0.0, 0, 500, 1, 40, 3, 50000, 2, 1, 1, 40000]])))
new_prediction = (new_prediction > 0.5)


In [26]:
from sklearn.metrics import confusion_matrix 
cm = confusion_matrix(y_test, y_pred) 
print (cm)


[[1523   52]
 [ 288  137]]
